"""Russian phonetic transcriptions of SIGCHI awardee names."""

NAME_RU: dict[str, str] = {
    "Aaditeshwar Seth": "Аадитешвар Сет",
    "Aakash Gautam": "Аакаш Гаутам",
    "Aaron Marcus": "Аарон Маркус",
    "Aaron Quigley": "Аарон Квигли",
    "Abigail Sellen": "Эбигейл Селлен",
    "Alan Dix": "Алан Дикс",
    "Alan F. Newell": "Алан Ф. Ньюэлл",
    "Albrecht Schmidt": "Альбрехт Шмидт",
    "Alexis Hiniker": "Алексис Хиникер",
    "Allison Druin": "Эллисон Друин",
    "Allison Woodruff": "Эллисон Вудрафф",
    "Amy J. Ko": "Эми Дж. Ко",
    "Amy Ogan": "Эми Оган",
    "Amy S. Bruckman": "Эми С. Бракман",
    "Andrea Colaco": "Андреа Колако",
    "Andrew D. Wilson": "Эндрю Д. Уилсон",
    "Andrew Monk": "Эндрю Монк",
    "Andy Cockburn": "Энди Кокберн",
    "Andy Dearden": "Энди Дирден",
    "Anicia Peters": "Анисия Питерс",
    "Aniket Kittur": "Аникет Киттур",
    "Anind K. Dey": "Анинд К. Дей",
    "Anna Cox": "Анна Кокс",
    "Anna Lisa Martin-Niedecken": "Анна Лиза Мартин-Нидекен",
    "Anna Maria Feit": "Анна Мария Файт",
    "Antti Oulasvirta": "Антти Оуласвирта",
    "Anupriya Tuli": "Ануприя Тули",
    "Arnold M. Lund": "Арнольд М. Лунд",
    "Arunesh Mathur": "Арунеш Матхур",
    "Austin Henderson": "Остин Хендерсон",
    "Azra Ismail": "Азра Исмаил",
    "Batya Friedman": "Батья Фридман",
    "Ben Shneiderman": "Бен Шнейдерман",
    "Ben Zhang": "Бен Чжан",
    "Benjamin B. Bederson": "Бенджамин Б. Бедерсон",
    "Bill Gaver": "Билл Гейвер",
    "Bill Hefley": "Билл Хефли",
    "Bill Verplank": "Билл Верпланк",
    "Björn Hartmann": "Бьёрн Хартманн",
    "Blase Ur": "Блейз Ур",
    "Bonnie John": "Бонни Джон",
    "Bonnie Nardi": "Бонни Нарди",
    "Brad A. Myers": "Брэд А. Майерс",
    "Brennan Schaffner": "Бреннан Шаффнер",
    "Brian Shackel": "Брайан Шэкел",
    "Carl DiSalvo": "Карл ДиСальво",
    "Carl Gutwin": "Карл Гатвин",
    "Catherine Plaisant": "Катрин Плезан",
    "Cecilia Aragon": "Сесилия Арагон",
    "Chris Elsden": "Крис Элсден",
    "Chris Harrison": "Крис Харрисон",
    "Christopher Schmandt": "Кристофер Шмандт",
    "Clare-Marie Karat": "Клер-Мари Карата",
    "Clarisse de Souza": "Кларисс де Соуза",
    "Clayton Lewis": "Клейтон Льюис",
    "Cliff Lampe": "Клифф Лэмп",
    "Courtney N. Reed": "Кортни Н. Рид",
    "Dan R. Olsen Jr.": "Дэн Р. Олсен-мл.",
    "Daniel M. Russell": "Дэниел М. Рассел",
    "Daniel Rosenberg": "Дэниел Розенберг",
    "Darren Gergle": "Даррен Гергл",
    "David Canfield Smith": "Дэвид Кэнфилд Смит",
    "David Kieras": "Дэвид Кирас",
    "Deborah J. Mayhew": "Дебора Дж. Мэйхью",
    "Dennis Wixon": "Деннис Уиксон",
    "Dhruv \"DJ\" Jain": "Дхрув «DJ» Джайн",
    "Don Patterson": "Дон Паттерсон",
    "Donald A. Norman": "Дональд А. Норман",
    "Douglas C. Engelbart": "Дуглас К. Энгельбарт",
    "Ed H. Chi": "Эд Х. Чи",
    "Elisabeth André": "Элизабет Андре",
    "Elizabeth F. Churchill": "Элизабет Ф. Черчилль",
    "Elizabeth Gerber": "Элизабет Гербер",
    "Elizabeth Mynatt": "Элизабет Майнатт",
    "Eric Horvitz": "Эрик Хорвиц",
    "Eric J. Gonzalez": "Эрик Дж. Гонсалес",
    "Eric Paulos": "Эрик Паулос",
    "Ernest Edmonds": "Эрнест Эдмондс",
    "Eunkyung Jo": "Ынгён Чжо",
    "Fabio Paternó": "Фабио Патерно",
    "Fernanda Viegas": "Фернанда Виегас",
    "Florian \"Floyd\" Mueller": "Флориан «Флойд» Мюллер",
    "Fred Hohman": "Фред Хоман",
    "Gary M. Olson": "Гэри М. Олсон",
    "Gary Marsden": "Гэри Марсден",
    "Gary Perlman": "Гэри Перлман",
    "Gene Lynch": "Джин Линч",
    "George Fitzmaurice": "Джордж Фицморис",
    "George Furnas": "Джордж Фёрнас",
    "George G. Robertson": "Джордж Дж. Робертсон",
    "Geraldine Fitzpatrick": "Джеральдин Фицпатрик",
    "Gerhard Fischer": "Герхард Фишер",
    "Gerrit C. Van Der Veer": "Геррит К. ван дер Веер",
    "Gilbert Cockton": "Гилберт Коктон",
    "Gillian Crampton Smith": "Джиллиан Крэмптон Смит",
    "Gillian R. Hayes": "Джиллиан Р. Хейс",
    "Gloria Mark": "Глория Марк",
    "Gregg Vanderheiden": "Грегг Вандерхайден",
    "Gregory Abowd": "Грегори Абоуд",
    "Gustavo Lopez": "Густаво Лопес",
    "Hans Gellersen": "Ханс Геллерсен",
    "Hasti Seifi": "Хасти Сейфи",
    "Helena Mentis": "Хелена Ментис",
    "Helen Petrie": "Хелен Петри",
    "Hiroshi Ishii": "Хироси Исии",
    "Hrvoje Benko": "Хрвое Бенко",
    "Hugh Dubberly": "Хью Дабберли",
    "Humphrey Curtis": "Хамфри Кёртис",
    "Indrani Medhi Thies": "Индрани Медхи Тис",
    "Jacki O'Neill": "Джеки О’Нил",
    "Jacob O. Wobbrock": "Джейкоб О. Вобброк",
    "Jaime Teevan": "Джейми Тивен",
    "Jakob Nielsen": "Якоб Нильсен",
    "James A. Landay": "Джеймс А. Лэндей",
    "James D. Foley": "Джеймс Д. Фоули",
    "James D. Hollan": "Джеймс Д. Холлан",
    "James Fogarty": "Джеймс Фогарти",
    "Jan Gulliksen": "Ян Гулликсен",
    "Jason Hong": "Джейсон Хонг",
    "Jasmine Lu": "Жасмин Лу",
    "Jean Scholtz": "Джин Шольц",
    "Jean-Daniel Fekete": "Жан-Даниэль Фекете",
    "Jeff A. Johnson": "Джефф А. Джонсон",
    "Jeff Heer": "Джефф Хир",
    "Jeffrey P. Bigham": "Джеффри П. Бигем",
    "Jennifer Mankoff": "Дженнифер Манкофф",
    "Jenny Preece": "Дженни Прис",
    "Jim Miller": "Джим Миллер",
    "Joanna McGrenere": "Джоанна МакГренер",
    "Jodi Forlizzi": "Джоди Форлицци",
    "John \"Scooter\" Morris": "Джон «Скутер» Моррис",
    "John C. Tang": "Джон К. Танг",
    "John C. Thomas": "Джон К. Томас",
    "John Gould": "Джон Гулд",
    "John Karat": "Джон Карата",
    "John M. Carroll": "Джон М. Кэрролл",
    "John Stasko": "Джон Стаско",
    "John T. Richards": "Джон Т. Ричардс",
    "Jon E. Froehlich": "Джон Э. Фрёлих",
    "Jonathan Grudin": "Джонатан Грудин",
    "Jonathan Lazar": "Джонатан Лазар",
    "Jooyoung Park": "Джуён Пак",
    "Joseph A. Konstan": "Джозеф А. Констан",
    "Joseph J. LaViola Jr.": "Джозеф Дж. ЛаВиола-мл.",
    "Josh Andres": "Джош Андрес",
    "Joy Mountford": "Джой Маунтфорд",
    "Joëlle Coutaz": "Жоэль Кута",
    "Juan Gilbert": "Хуан Гилберт",
    "Judith S. Olson": "Джудит С. Олсон",
    "Julie A. Kientz": "Джули А. Кинц",
    "Jun Rekimoto": "Дзюн Рэкимото",
    "Kaj Grønbaek": "Кай Грёнбек",
    "Kai Lukoff": "Кай Лукофф",
    "Karan Ahuja": "Каран Ахуджа",
    "Karen Holtzblatt": "Карен Хольцблатт",
    "Kasper Hornbæk": "Каспер Хорнбек",
    "Katerina Stepanova": "Катерина Степанова",
    "Kate Starbird": "Кейт Старбёрд",
    "Katherine Isbister": "Кэтрин Исбистер",
    "Katta Spiel": "Катта Шпиль",
    "Ken Hinckley": "Кен Хинкли",
    "Ken Pfeuffer": "Кен Пфойфер",
    "Kentaro Toyama": "Кэнтаро Тояма",
    "Kevin Schofield": "Кевин Скофилд",
    "Kori Inkpen": "Кори Инкпен",
    "Kristina Höök": "Кристина Хёк",
    "Kyle Johnson": "Кайл Джонсон",
    "Larry Tesler": "Ларри Теслер",
    "Laura Dabbish": "Лора Дэббиш",
    "Leona Holloway": "Леона Холлоуэй",
    "Leysia Palen": "Лейсия Пален",
    "Liban Hussein": "Либан Хусейн",
    "Loren Terveen": "Лорен Тервин",
    "Lorraine Borman": "Лоррейн Борман",
    "Lorrie Faith Cranor": "Лорри Фейт Крейнор",
    "Lucy A. Suchman": "Люси А. Сачман",
    "Maneesh Agrawala": "Маниш Агравала",
    "Mar Gonzalez-Franco": "Мар Гонсалес-Франко",
    "Marc Hassenzahl": "Марк Хассенцаль",
    "Margaret Burnett": "Маргарет Бёрнетт",
    "Maria Cecília Calani Baranauskas": "Мария Сесилия Калани Баранаускас",
    "Maria Francesca Costabile": "Мария Франческа Костабиле",
    "Marian Williams": "Мариан Уильямс",
    "Marilyn Mantei Tremaine": "Мэрилин Мантей Тремейн",
    "Maristella Matera": "Маристелла Матера",
    "Mark Ackerman": "Марк Аккерман",
    "Mark Billinghurst": "Марк Биллингхёрст",
    "Mark Colley": "Марк Колли",
    "Marti A. Hearst": "Марти А. Хёрст",
    "Martin Feick": "Мартин Файк",
    "Martin Wattenberg": "Мартин Ваттенберг",
    "Mary Beth Rosson": "Мэри Бет Россон",
    "Mary Czerwinski": "Мэри Червински",
    "Massimiliano Di Luca": "Массимилиано Ди Лука",
    "Megan Hofmann": "Меган Хофманн",
    "Meredith Ringel Morris": "Мередит Рингел Моррис",
    "Michael Atwood": "Майкл Этвуд",
    "Michael Muller": "Майкл Мюллер",
    "Michel Beaudoin-Lafon": "Мишель Бодуэн-Лафон",
    "Morten Kyng": "Мортен Кюнг",
    "Munmun De Choudhury": "Мунмун Де Чоудхури",
    "Nadia Campo Woytuk": "Надя Кампо Войтук",
    "Nadya Peek": "Надя Пик",
    "Nicholas Vincent": "Николас Винсент",
    "Nicola Dell": "Никола Делл",
    "Niklas Elmqvist": "Никлас Эльмквист",
    "Norbert A. Streitz": "Норберт А. Штрайц",
    "Nur Yildirim": "Нур Йылдырым",
    "Nuria Oliver": "Нурия Оливер",
    "Patrick Baudisch": "Патрик Баудиш",
    "Pattie Maes": "Пэтти Маес",
    "Paul Dourish": "Пол Дауриш",
    "Paul Resnick": "Пол Ресник",
    "Paul Strohmeier": "Пауль Штромайер",
    "Per Ola Kristensson": "Пер Ола Кристенссон",
    "Peter G. Polson": "Питер Дж. Полсон",
    "Peter L. Pirolli": "Питер Л. Пиролли",
    "Peter Wright": "Питер Райт",
    "Philippe Palanque": "Филипп Паланк",
    "Phoebe Sengers": "Фиби Сенгерс",
    "Phoebe Toups Dugas": "Фиби Тупс Дюга",
    "Qian Yang": "Цянь Ян",
    "Randy Pausch": "Рэнди Пауш",
    "Ravin Balakrishnan": "Равин Балакришнан",
    "Rebecca E. Grinter": "Ребекка Э. Гринтер",
    "Regan Mandryk": "Риган Мандрик",
    "Richard H.R. Harper": "Ричард Х. Р. Харпер",
    "Richard I. Anderson": "Ричард Ай. Андерсон",
    "Richard Ladner": "Ричард Ладнер",
    "Robert E. Kraut": "Роберт Э. Краут",
    "Robert J.K. Jacob": "Роберт Дж. К. Джейкоб",
    "Robert Xiao": "Роберт Сяо",
    "Robin Jeffries": "Робин Джеффрис",
    "Roel Vertegaal": "Рул Вертегал",
    "Ronald M. Baecker": "Рональд М. Бекер",
    "Rosalind Picard": "Розалинда Пикар",
    "Ryen W. White": "Райен У. Уайт",
    "Sara Bly": "Сара Блай",
    "Sara J. Czaja": "Сара Дж. Чая",
    "Sara Kiesler": "Сара Кислер",
    "Saul Greenberg": "Сол Гринберг",
    "Scott E. Hudson": "Скотт Э. Хадсон",
    "Scott MacKenzie": "Скотт Маккензи",
    "Shaimaa Lazem": "Шаймаа Лазем",
    "Sharon Oviatt": "Шэрон Овиатт",
    "Shaowen Bardzell": "Шаовень Бардзелл",
    "Sheelagh Carpendale": "Шила Карпендейл",
    "Shumin Zhai": "Шуминь Чжай",
    "Shwetak Patel": "Шветак Пател",
    "Sonya S. Kwak": "Соня С. Квак",
    "Stefanie Mueller": "Штефани Мюллер",
    "Stephen Brewster": "Стивен Брюстер",
    "Steve Benford": "Стив Бенфорд",
    "Steve Hodges": "Стив Ходжес",
    "Steve Whittaker": "Стив Уиттакер",
    "Steven K. Feiner": "Стивен К. Файнер",
    "Steven M. Drucker": "Стивен М. Дракер",
    "Steven Pemberton": "Стивен Пембертон",
    "Stuart K. Card": "Стюарт К. Кард",
    "Sukran Karaosmanoglu": "Шюкран Караосманоглу",
    "Sunny Consolvo": "Санни Консольво",
    "Susan M. Dray": "Сьюзан М. Дрей",
    "Susan R. Fussell": "Сьюзан Р. Фасселл",
    "Susan T. Dumais": "Сьюзан Т. Дюме",
    "Susanne Bødker": "Сюзанна Бёдкер",
    "Takeo Igarashi": "Такэо Игараси",
    "Tanzeem Choudhury": "Танзим Чоудхури",
    "Ted Henter": "Тед Хентер",
    "Ted Nelson": "Тед Нельсон",
    "Terry Winograd": "Терри Виноград",
    "Thad Eugene Starner": "Тэд Юджин Старнер",
    "Thomas Green": "Томас Грин",
    "Thomas K. Landauer": "Томас К. Ландауэр",
    "Thomas P. Moran": "Томас П. Моран",
    "Thomas S. Tullis": "Томас С. Таллис",
    "Tiago Guerreiro": "Тиагу Геррейру",
    "Tom Hewett": "Том Хьюитт",
    "Tom Rodden": "Том Родден",
    "Uichin Lee": "Ыйджин Ли",
    "Vassilis Kostakos": "Вассилис Костакос",
    "Vicente Arroyos": "Висенте Арройос",
    "Vicki L. Hanson": "Вики Л. Хансон",
    "Victoria Bellotti": "Виктория Беллотти",
    "Volker Wulf": "Фолькер Вульф",
    "W. Keith Edwards": "У. Кит Эдвардс",
    "Wendy Ju": "Венди Джу",
    "Wendy Kellogg": "Венди Келлог",
    "Wendy Mackay": "Венди Маккей",
    "William A.S. Buxton": "Уильям А. С. Бакстон",
    "William Newman": "Уильям Ньюман",
    "Wolfgang Stuerzlinger": "Вольфганг Штюрцлингер",
    "Yixin Zou": "Исинь Цзоу",
    "Yoshifumi Kitamura": "Ёсифуми Китамура",
    "Yves Guiard": "Ив Гиар",
    "Yvonne Rogers": "Ивонн Роджерс",
    "Zhengjie Liu": "Чжэнцзе Лю",
    "Zijie Jay Wang": "Цзыцзе Джей Ван",
}


def name_ru(english: str) -> str:
    return NAME_RU.get(english, english)
